export const TITLE_OPTIONS = [
    'Stuck with a decision? Let RandoMe help you',
    'Let Fate Take the Wheel',
    'Decision-Making Made Easy',
    'Spice Up Your Choices with a Dash of RandoMe',
    'Roll the Dice of Destiny with RandoMe',
    'When in Doubt, RandoMe It Out',
    'Our Partner in Quirky Decision-Making Adventures',
    'Surrender to Serendipity with RandoMe',
    'Trust RandoMe for a Dash of Spontaneity',
    'Ride the Rollercoaster of Choices with RandoMe',
    'Life is a Journey, Let RandoMe Be Your Guide',
    'Let RandoMe Steer the Ship to the Unknown.',
    'Where Possibilities Meet Probability',
];